### PR TITLE
Jamisonv/feature/request js support

### LINKED ISSUE #200: Delta and Zeta imagery not found
after `pstorm collect -s 2020` Delta and Zeta imagery not found

Screenshot from 2020-10-29 19-32-30

### PR DESCRIPTION
**Pull request by jamisonvalentine**
using requests-html in addition to regular requests module for support of js rendering

### CODE REVIEW

**Review by ebgoldstein — DISMISSED** [review]

**Comment by ebgoldstein** [comment]
it's failing on `test_connection_handler.py`

new (deprecation) error:

>pyee.EventEmitter is deprecated and will be removed in a future major version; you should instead use either pyee.AsyncIOEventEmitter, pyee.TwistedEventEmitter, pyee.ExecutorEventEmitter, pyee.TrioEventEmitter, or pyee.BaseEventEmitter.


Screen Shot 2021-01-04 at 11 01 31 PM

**Comment by ebgoldstein** [comment]
hmmm... I'm not sure what to do here...
one idea is try try a different library/approach: 

e.g., https://docs.scrapy.org/en/latest/topics/dynamic-content.html#pre-rendering-javascript

what do you think @jamisonvalentine ?

**Comment by jamisonvalentine** [comment]
> hmmm... I'm not sure what to do here...
> one idea is try try a different library/approach:
> 
> e.g., https://docs.scrapy.org/en/latest/topics/dynamic-content.html#pre-rendering-javascript
> 
> what do you think @jamisonvalentine ?

I considered that approach as well but wanted to see if we could circumvent that deprecation error somehow before trying another library...

doesn't look like it would be too hard to incorporate, hopefully just minor changes to both functions in [response_getter.py](https://github.com/UNCG-DAISY/psi-collect/blob/master/psicollect/collector/response_getter.py)

**Comment by ebgoldstein** [comment]
i will spend time today w/ the tests

**Comment by ebgoldstein** [comment]
ignoring the exit flags (from dep warning) in tox.ini causes coverage to get very low — which is not cool, and we should avoid that. so i reverted that change and will now trying to ignore dep warning in `pytest.ini`
https://docs.pytest.org/en/stable/warnings.html

**Comment by ebgoldstein** [comment]
ok, so deprecation is taken care of, now there is a new build error only with py 3.8...

**Comment by ebgoldstein** [comment]
the py38 build is timing out:
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by ebgoldstein** [comment]
ook, I'm almost sure this has to do with installing `requests-html`

**Review by ebgoldstein — APPROVED** [review]
i am merging this. the build is still not working for py38, but i have used it w/ py38... I'll make an issue...

**Pull request merged**
