### PR TITLE
Minor changes to paper.md (mostly gramatical)

### PR DESCRIPTION
**Pull request by conlin-matt**
See my commit comment below; just minor edits here. 

Submitting this pull request as part of the JOSS review process (openjournals/joss-reviews#2075)

### CODE REVIEW

**Comment by ebgoldstein** [comment]
@conlin-matt — thank you for these edits. You make a good point re: the SIS...

 I adjusted your edit to the SIS line a bit, LMK if this works for you:

> ... categorize impact in the context of the @Sallenger2000 Storm 
Impact Scale...

If it does, I'll merge.
If not, LMK how i can change that will work for you.

**Review by ebgoldstein — CHANGES_REQUESTED** [review]
see my comments re: SIS line...

**Comment by conlin-matt** [comment]
@ebgoldstein Yeah, I think that text is good- true to the nature of the SIS and concise.

**Review by ebgoldstein — APPROVED** [review]
very cool — this SIS is better for sure..

**Pull request merged**
